import 'package:hive/hive.dart';
import 'package:intl/intl.dart';

part 'activity.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for each HiveObject
class Activity extends HiveObject { // Extend HiveObject for easier Hive operations
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String description;

  @HiveField(2)
  final DateTime timestamp;

  // Constructor now doesn't need to be const if you extend HiveObject directly
  // and want Hive to manage keys.
  // However, for our current ID generation (based on timestamp), it's fine.
  Activity({required this.id, required this.description, required this.timestamp});

  String get formattedDate {
    return DateFormat('yyyy-MM-dd').format(timestamp);
  }

  String get formattedTime {
    return DateFormat('hh:mm a').format(timestamp);
  }
}