import 'package:hive/hive.dart';

part 'task_entry.g.dart'; // Generated by build_runner

@HiveType(typeId: 0)
class TaskEntry extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String description;

  @HiveField(2)
  final DateTime timestamp;

  TaskEntry({
    required this.id,
    required this.description,
    required this.timestamp,
  });

  // For Firestore serialization
  Map<String, dynamic> toJson() => {
    'id': id,
    'description': description,
    'timestamp': timestamp.toIso8601String(),
  };

  factory TaskEntry.fromJson(Map<String, dynamic> json) => TaskEntry(
    id: json['id'] as String,
    description: json['description'] as String,
    timestamp: DateTime.parse(json['timestamp'] as String),
  );
}