import 'package:hive/hive.dart';

part 'user_prefs.g.dart'; // Generated by build_runner

@HiveType(typeId: 2)
class UserPrefs extends HiveObject {
  @HiveField(0)
  String lastUserId;

  @HiveField(1)
  String? lastUserEmail; // Email can be null

  // Note: DisplayName is fetched directly from Firebase Auth User object, not stored here.
  // This keeps UserPrefs simpler and relies on Firebase as the source of truth for profile info.

  UserPrefs({
    required this.lastUserId,
    this.lastUserEmail,
  });
}